export const DANGER = 'DANGER'
export const WARNING = 'WARNING'
export const SUCCESS = 'SUCCESS'
export const INFO = 'INFO'
export const PRIMARY = 'PRIMARY'
export const SECONDARY = 'SECONDARY'
export const FLEX = 'FLEX'
